@baseurl = http://localhost:4000/api
@authToken =  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2ZhNjAzMTU1M2QxMGEzZGQ1MTQzOTIiLCJ1c2VyRW1haWwiOiJnYXVyYXZ4b3JAZ21haWwuY29tIiwiaWF0IjoxNjc3MzU2NDQxLCJleHAiOjE2NzczNTcwNDF9.gS7xT3hut_el2nlQMaSfdhWqRDUoIy6CvDTeVU4qlIY
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2ZhNjAzMTU1M2QxMGEzZGQ1MTQzOTIiLCJ1c2VyRW1haWwiOiJnYXVyYXZ4b3JAZ21haWwuY29tIiwiaWF0IjoxNjc3MzU2NDQxLCJleHAiOjE2NzczNTcwNDF9.MwtTELkFpDhB9j08k23BRzjmb9SXbhqAJymM7U8avOU


### Home Page Endpoints
GET http://localhost:4000/




### SignUp Endpoint
POST {{baseurl}}/auth/signup
Content-Type: application/json

{
	"userName": "timecop",
	"password": "timecop@123",
	"name": {
		"firstName": "Gaurav",
		"middleName": "Kumar",
		"lastName": "Aggarwal"
	},

	"contact": {
		"email": "gauravxor@gmail.com",
		"phone": "1020304050"
	},
	"address": {
		"addressMain": "1234 main street",
		"country": "India",
		"state": "Delhi",
		"city": "Delhi",
		"pincode": "12345"
	},

	"dob": "2023-02-18",
	"createdAt": "2020-12-02",
	"updatedAt": "2020-12-02",
	"bookings":{
		"bookingDate": "2020-12-02",
		"dateOfVisit": "2020-12-02",
		"children": "100",
		"adults": "2"
	}
}



### Verify OTP Endpoint
POST {{baseurl}}/auth/verify-otp
Content-Type: application/json
# Set-Cookie: authToken={{authToken}} refreshToken={{refreshToken}}

{
  "email": "gauravxor@gmail.com",
  "otp": "09o69gll"
}



### Login Endpoint
POST {{baseurl}}/auth/login
Content-Type: application/json

{
  "email": "gauravxor@gmail.com",
  "password": "timecop@123"
}




### Logout Endpoint
POST {{baseurl}}/auth/logout
# Set-Cookie: authToken={{authToken}} refreshToken={{refreshToken}}
Content-Type: application/json

{
  "email": "gauravxor@gmail.com"
}



### Resent Otp Endpoint
POST {{baseurl}}/auth/resend-otp
# Set-Cookie: authToken={{authToken}} refreshToken={{refreshToken}}
Content-Type: application/json

{
  "email": "gauravxor@gmail.com"
}



### User data update Endpoints
POST {{baseurl}}/update/user
Content-Type: application/json
# Set-Cookie: authToken={{authToken}} refreshToken={{refreshToken}}

{
	"firstName": "John",
	"middleName": "Kumar",
	"lastName": "Doe",
	"email": "johndoe@mgail.com",
	"phone": "1234567890",
	"address": "1234, 5th Street, New York, NY, 12345",
	"country": "USA",
	"state": "NY",
	"city": "New York",
	"pincode": "12345"
}